# Kanagawa Tmux
set -g status on
set -g status-position bottom
set -g status-style bg=#1f1f28,fg=#dcd7ba

# Links: Session-Name
set -g status-left "#[fg=#7e9cd8,bold] #S "

# Rechts: Uhrzeit
set -g status-right "#[fg=#7e9cd8] %H:%M "

# Fenster
set -g status-justify centre
setw -g window-status-format "#[fg=#54546d] #I:#W "
setw -g window-status-current-format "#[fg=#7e9cd8,bold] #I:#W "
